[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
    colorscheme hybrid
    set background=dark
'''

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap T :NERDTreeFocus<CR>
  let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

